language: java
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c "ALTER ROLE postgres PASSWORD 'foo'" -U postgres
install:
  # Cypher
  - cd cypher
  - ./get-neo4j.sh
  - . environment-variables-neo4j.sh
  - ./configure-neo4j.sh
  - cd ..
  # environment vars
  - export POSTFIX=_0_0.csv
script:
  # Postgres
  - chmod 755 ~
  - cd postgres/load-scripts
  - export PG_CSV_DIR=$(pwd)/../test-data
  - ./load.sh
  - cd ../..
  # Cypher
  - cd cypher
  - . environment-variables-neo4j.sh
  - cp test-data/raw/*.csv test-data/converted
  - export NEO4J_DATA_DIR=`pwd`/test-data/converted
  - cd load-scripts
  - ./convert-csvs.sh
  - ./import-to-neo4j.sh
  - ./restart-neo4j.sh
  - cd ../..
  # tests
  - mvn test -B
notifications:
  slack: ldbcouncil:JRXP43nDV4KRgtclmoNZJpyq
  email: false
  on_success: change
  on_failure: always
