version: "3.9"

services:
  umbra-db:
    image: ${UMBRA_DOCKER_IMAGE}
    container_name: snb-interactive-umbra
    ports:
      - "5432:5432"
    volumes:
      - type: bind
        source: ${UMBRA_CSV_DIR}
        target: /data/
      - type: bind
        source: ${UMBRA_DDL_DIR}
        target: /ddl/
      - type: bind
        source: ${UMBRA_DATABASE_DIR}
        target: /var/db/

    command: [
      "/bin/sh",
      "-c",
      "echo Cleanup commence \
       && rm -rf /var/db/* /var/log/* \
       && echo Cleanup done \
       && umbra_sql --createdb /var/db/ldbc.db /ddl/create-role.sql /ddl/schema.sql \
       && echo Database created \
       && umbra_server --address 0.0.0.0 /var/db/ldbc.db >/dev/null"
    ]

  db-load:
    build: ./scripts
    image: "umbra-db-loader:latest"
    container_name: umbra-db-loader
    volumes:
      - type: bind
        source: ${UMBRA_DDL_DIR}
        target: /ddl/
    depends_on:
      - umbra-db
    command: sh -c "/wait && python3 home/load.py ${UMBRA_CSV_DIR}"
    environment:
      - UMBRA_HOST=umbra-db
      - WAIT_HOSTS=umbra-db:5432
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30