version: "3.9"

services:
  postgres-db:
    image: ${POSTGRES_DOCKER_IMAGE}
    container_name: snb-interactive-postgres
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - type: bind
        source: ${POSTGRES_CSV_DIR}
        target: /data/
      - type: bind
        source: ${POSTGRES_CUSTOM_CONFIGURATION}
        target: /etc/postgresql.conf
      # Uncomment to persist data
      # - type: bind
      #   source: ${POSTGRES_CSV_DIR}
      #   target: /var/lib/postgresql/data
      - type: bind
        source: ${POSTGRES_SCRIPTS_DIR}/create-postgresdb.sh
        target: /docker-entrypoint-initdb.d/init-user-db.sh
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DOCKER_PLATFORM_FLAG=${POSTGRES_DOCKER_PLATFORM_FLAG}
      - tz=Etc/GMT+0
    command: [
      "postgres",
      "-c",
      "${POSTGRES_CUSTOM_ARGS}"
    ]

  db-load:
    build: ./scripts
    image: "postgres-db-loader:latest"
    container_name: postgres-db-loader
    volumes:
      - type: bind
        source: ${POSTGRES_DDL_DIR}
        target: /ddl/
      - type: bind
        source: ${POSTGRES_DML_DIR}
        target: /dml/
      - type: bind
        source: ${POSTGRES_CSV_DIR}
        target: /data/
    depends_on:
      - postgres-db
    command: sh -c "/wait && python3 -u home/load.py --POSTGRES_CSV_DIR ${POSTGRES_CSV_DIR} --is_container True"
    environment:
      - POSTGRES_HOST=postgres-db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - WAIT_HOSTS=postgres-db:${POSTGRES_PORT}
      - WAIT_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=5
      - WAIT_HOST_CONNECT_TIMEOUT=30
      - tz=Etc/GMT+0
